name: Lint, Build and Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Lint and Build
        run: |
          cd app
          yarn
          yarn lint
          yarn build
        env:
          REACT_APP_OPEN_WEATHER_API_TOKEN: ${{ secrets.REACT_APP_OPEN_WEATHER_API_TOKEN }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THESYNC }}'
          channelId: live
          projectId: thesync
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels